---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo-shard2
  namespace: default
  labels:
    sharding.fluxcd.io/key: shard2
spec:
  interval: 5m0s
  url: https://github.com/stefanprodan/podinfo
  ref:
    tag: "6.4.0"
